### ISSUE TITLE
Distribute this as a PyPi package

### ISSUE THREAD

**Issue by patrickayoup** [neilernst/cliffsDelta#2]
Hi,

I find this library very useful, thanks for providing it.
Would it be possible for you to distribute this package on pypi; it would be more convenient to be able to pip install it like all other dependencies.

I can help with this task if needed.

Thanks

**Comment by suhaibmujahid** [comment]
This will be great, it will be easier to use.

What do you think @neilernst?

**Comment by neilernst** [comment]
sure, i'll put it on the backlog - but welcome a PR.

**Comment by patrickayoup** [comment]
@neilernst I can possibly send you a PR later this week. Thanks

**Comment by prkhrv** [comment]
Can I make a PR? For python Package??

**Comment by patrickayoup** [comment]
I haven't been able to find the time to do this personally, I think @neilernst said a PR is welcome, so you definitely won't be duplicating any work on my side

**Comment by prkhrv** [comment]
Cool I will add a PR by Tomorrow.
